apiVersion: v1
kind: Service
metadata:
  name: portal-app-service
  namespace: portal-app
spec:
  type: NodePort
  selector:
    app: portal-app
  ports:
    # Below Port number is a service port number
    - port: 80
      # Below targetPort is a Container Port number
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007


