apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-local-claim
  namespace: portal-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
