apiVersion: v1
kind: Service
metadata:
  name: portal-database-service
  namespace: portal-database
spec:
  selector:
    app: portal-database
  ports:
    # Below Port number is a service port number
    - port: 80
      # Below targetPort is a Container Port number
      targetPort: 5432
