apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-local-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
