apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ebs-pvc-sc
  namespace: portal-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: "postgres-ebs-sc"
